### PR TITLE
Fix QueueInteropTransport & rename vars to avoid confusion

### LINKED ISSUE #39: Issue with multiple senders - enveloping same message more than once
I have multiple senders configured and everything was working fine until I updated to the latest messenger version.

After some debugging, I realized that the message is being enveloped more than once [here](https://github.com/php-enqueue/messenger-adapter/blob/77a596507b0e7b8bbddae573579f81ce7a082959/QueueInteropTransport.php#L153).

I also noticed that the `$message` variable gets redefined [here](https://github.com/php-enqueue/messenger-adapter/blob/77a596507b0e7b8bbddae573579f81ce7a082959/QueueInteropTransport.php#L119) - it was originally an `Envelope` instance containing my original message under the `message` parameter and it becomes an instance of `\Interop\Amqp\Impl\AmqpMessage`, which gets enveloped and returned in the end of this method.

It seems that the issue also started after [this change on the MiddlewareInterface](https://github.com/symfony/messenger/commit/b61ae3a6ec20107a9136805b53659eb101370b80#diff-2464a1b929b3b4bcf55a6104ad89e24e), as the `$envelope` variable now gets redefined after each iteration.

### PR DESCRIPTION
**Pull request by ogizanagi**
Fixes https://github.com/symfony/symfony/issues/29666
Fixes #39

### CODE REVIEW

File: QueueInteropTransport.php [hunk 1]
```diff
@@ -140,17 +139,17 @@ public function send(Envelope $message): Envelope
         }
 
         try {
-            $producer->send($topic, $message);
+            $producer->send($topic, $interopMessage);
         } catch (InteropQueueException $e) {
             if ($this->contextManager->recoverException($e, $destination)) {
                 // The context manager recovered the exception, we re-try.
-                $this->send($message);
+                $envelope = $this->send($envelope);
```
Comment (ogizanagi) [inline QueueInteropTransport.php]: Note: is it really expected to throw below in case of recoverable exception & retry? 🤔 Or is this missing a `return` instead?

Comment (Tobion) [reply QueueInteropTransport.php]: this looks wrong indeed

Comment (Tobion) [reply QueueInteropTransport.php]: also there is possibly an endless loop if recoverException keeps returning true. maybe there should be a safe-guard counter.

**Comment by tkocjan** [comment]
I reported this problem on symfony/symfony [messenger] and have tested this fix and it fixes my problem. Thanks!

**Comment by Tobion** [comment]
There is a CS error

**Comment by drgomesp** [comment]
Thanks, @ogizanagi.

**Comment by haroldmodesto** [comment]
@drgomesp When is this going to be released? I'd like to not use master if it can be helped.

**Comment by drgomesp** [comment]
@haroldmodesto done.
